### ISSUE TITLE
Build a parcels data output

### ISSUE THREAD

**Issue by iandees** [openaddresses/machine#163]
Lots of our address point sources are actually parcel polygons that we take the centroid of when we include them in the OpenAddresses dataset. There's tons of interest in building a parcel polygon dataset, so lets tweak machine to output a parcel polygon dataset alongside the address point dataset.

This ticket should serve as a discussion for how we might implement that.

**Comment by iandees** [comment]
I think the parcel conform information should be stored separately from the current `conform` object in the source JSON blobs. I see two options:

1. we include a `parcel_conform` object in the existing source document. This allows us to maintain a single record for license, name, coverage, etc. information
2. we create a second repo alongside the existing `openaddresses/openaddresses` repo that is specific to parcels. The sources there could be a copy of the sources in the existing repo but the `conform` objects are specific to parcel data. A second repo would allow us to tailor the documentation a bit better (i.e. CONTRIBUTING.md could be parcel-specific, pull requests could be parcel-specific, etc.)

Other than that, we need to think about:
1. What is the MVP for the output format? Addresses had number, street, lat, lon. What's the equivalent for parcels?
2. How do we adjust machine to do this without making it too crazy to maintain?

**Comment by migurski** [comment]
Couple of disjointed thoughts on this:

* Parcel datasets usually have a unique ID or APN in them. We might want an [`id` in the conform object attribute tags](https://github.com/openaddresses/openaddresses/blob/master/CONTRIBUTING.md#attribute-tags) to reference this.
* In the [July 15 run](http://data.openaddresses.io/runs/1436940473.228/index.html), there were [148 datasets with polygon geometries](http://data.openaddresses.io/runs/1436940473.228/state.txt), most of them in the US. A different testing run showed 158 of these. They are likely to be parcels.
* The polygon data is separated quite late in the process, and it would be reasonable to hold onto it for a secondary download.

**Comment by migurski** [comment]
I guess I’d be in support of a single sources collection in one repo, with some parcel-oriented things in the file. Might this be a sensible setup?

```
{
  "conform":
  {
    "address": { … },
    "parcel": { "id": … },
    …
  }
  …
}
```

**Comment by iandees** [comment]
Yep, that makes sense. And we can assume `conform` contents are all-address until we see a `parcel` underneath. :+1:

**Comment by migurski** [comment]
Yes. So all the current sources would stay valid.

**Comment by jonahadkins** [comment]
I've worked with some companies that have monthly $$ contracts for [this dataset](http://www.corelogic.com/downloadable-docs/parcel-point-updates/q2-2015/parcel-point-datasheet.pdf) - might be of use for info / modeling?

**Comment by migurski** [comment]
As a thing to compare against, that would be interesting. Maybe a process like @mukih’s [analysis of OSM quality](http://www.ucl.ac.uk/~ucfamha/OSM%20data%20analysis%20070808_web.pdf).

**Comment by NelsonMinar** [comment]
I like the idea! And I have a strong preference for just adding parcel data to the existing source documents; not a new directory. One complicating factor; some data authorities will have separate datafiles / ESRI endpoints for addresses and parcels, multiple URLs. So I'm not sure it's enough to just have a separate section for parcel conform extraction info.

MVP for output? I'd say either a shapefile or GeoJSON FeatureCollection that contains a list of all parcels in the source data. CSV would work too, with EWKT or GeoJSON as the geometry column. What properties do we want in the output? Vendor id, street address, geometry. Anything else?

**Comment by migurski** [comment]
With separate data files or endpoints, I think it would be reasonable to have separate sources like `us-ca-oakland-addresses.json` and `us-ca-oakland-parcels.json`. That could be a decision left up to the contributor, and there’s already a fair number of overlapping city/county data sets.

**Comment by geobrando** [comment]
1.  As OA is expanding to be a repository of parcel polygon datasets as well as address points, sources that lack address fields should be allowed.  For this to work, the CI tests could allow sources that lack these fields as long as an `id` is present and maybe also if the data is of type `shapefile-polygon` or the ESRI layer is a polygon `geometryType`.  Machine could just ignore sources without address data when building the address point collections.
  
1. Related to the above, address point layers are frequently created from parcel polygons and retain the parcel identifier numbers.  Are we interested in capturing these in the `id` field?  If not, is it sufficient to just allow this data to be included because it can later be ignored?

However, one complication of inferring parcels from geometry would be that I believe there are some polygon sources that are actually building footprints and not parcels. I think the schema might need to be expanded to include a field indicating that the data are parcels.  The `id` field could potentially serve that purpose with proper documentation and the right testing in place.

**Comment by migurski** [comment]
This effort is now being discussed over in https://github.com/openaddresses/openaddresses/issues/1587.
