### ISSUE TITLE
Update dot map on a schedule

### ISSUE THREAD

**Issue by migurski** [openaddresses/machine#210]
Adapt [@sbma44’s `make_mbtiles.sh` script](https://github.com/openaddresses/openaddresses.io/blob/gh-pages/_src/make_mbtiles.sh) to a set of chef recipes and a thing we can run.

**Comment by migurski** [comment]
See also: https://github.com/openaddresses/openaddresses.io/pull/56

**Comment by migurski** [comment]
Apt packages needed to build tippecanoe: `git build-essential libsqlite3-dev protobuf-compiler libprotobuf-dev`.

**Comment by migurski** [comment]
@ericfischer, do you have any advice on Tippecanoe resource usage over time? For a data set of ~200M points with OA’s distribution, I’d like to figure out whether to run it on hardware, on a temporary overpowered EC2 instance, or on the same minimal EC2 instance that a bunch of other OA stuff runs on.

**Comment by ericfischer** [comment]
@migurski Sorry for the slow reply. If there is no metadata for each point, just geometry, and if you use the default resolution of z14, my experience is that it takes about 19 bytes of temporary storage per feature, so in this case 3.5GB. It is very useful to be able to have two copies in memory at the same time so that it doesn't thrash while sorting or streaming, so it should work well on a machine with at least 7GB of free memory and equally much free temporary disk space.

**Comment by migurski** [comment]
Thank you! That’s great info—sounds like I shouldn’t run it on a low memory machine. I’m sending GeoJSON features like this for each point:

    {"type": "Feature", "geometry": {"type": "Point", "coordinates": [x, y]}, "properties": {}}

Tippecanoe doesn’t like the properties to be omitted, and it doesn’t like bare point features either. Would there ever be a situation where I would want to pass in properties?

**Comment by ericfischer** [comment]
@migurski That's how I would format it too. Tippecanoe complains if there is no "properties" element only because the GeoJSON spec says that there should be one even if there are no properties. I can remove that check if it's a problem for you.

You would want properties if you had some particular attribute of the address data you wanted to visualize, like single family vs. apartment buildings, but if you just want a map of all address points, I think it's appropriate not to have any properties.

It will work with less memory; it will just be slow because it will continually have to page in data in from disk instead of having it in memory.

**Comment by migurski** [comment]
Thanks, useful! Could it ever take bare geometries as an alternative?

**Comment by ericfischer** [comment]
@migurski Maybe. The parsing is messy, but it's less bad than I was thinking it was. If you reach the end of a geometry, and its parent object isn't a hash with a "geometry" tag, it can't be the geometry of a Feature, and if its parent object isn't an array whose parent is a hash with a "geometries" tag, then it also can't be one of the geometries of a GeometryCollection. I should probably try to write that logic and see how complicated it gets.

**Comment by migurski** [comment]
I ran a test of Tippecanoe on the complete dataset last night, using the OSM US server. @ericfischer I’d love your opinion on whether these numbers look as you’d expect. The resulting `.mbtiles` file is 1.6GB.

The loading step took 3½ hours, using a consistent 24MB of memory the entire time. Addresses loaded linearly over time, up to 200m. I couldn’t find any use of a temp file during this time—where does it go?

<img width="629" alt="loading2" src="https://cloud.githubusercontent.com/assets/58730/10123867/a2b28ba2-64f9-11e5-99f6-f39e52233543.png">

The processing step took a little over an hour, maxing out at 8.5GB of memory or 46 bytes per address in the first 15 minutes but then settling down to about 300MB for the remaining time:

<img width="619" alt="processing" src="https://cloud.githubusercontent.com/assets/58730/10123877/fa03be12-64f9-11e5-9110-7aa9b698be69.png">

**Comment by ericfischer** [comment]
The temporary files are in `/tmp` or wherever you specify with `-t`. They are deleted on creation so they are only a nameless inode most of the time, but you can see their original names in `/proc/*/fd` if you look.

The memory seems fairly believable. During parsing, the only thing that is in memory is the JSON parse tree itself; the rest is being streamed to disk.

The intensive part is immediately after that ("Reordering geometry"), where it maps the geometry file into memory and writes it out to a new temporary file ordered by quadtree index instead of the input order. This can thrash a lot because it is not sequential at all unless the original data was in close to that order. That's probably where you saw 8.5GB of memory used, and I should do a new release because it could be smaller than 46 bytes now.

Then the tiling part is basically sequential: reading from temporary files and writing to new temporary files, and at each moment having only the features that will actually appear in the final output of a single tile in memory at any one moment. It is not a very efficient format in memory (64-bit drawing instructions, 64-bit coordinates) but I didn't try to crunch it because it's only a tile at a time.

The time seems fairly believable. Parsing GeoJSON is slow because JSON is complicated. I should make another input format that doesn't spend so much time on punctuation.

**Comment by migurski** [comment]
Sounds like it’s doing generally the right things! I don’t think there’s much I should be doing to optimize this. The ability to stream in WKT or WKB might be nice, but not necessary. I’ll keep charging ahead.
