### ISSUE TITLE
Add subaddress/unit column to CSV output

### ISSUE THREAD

**Issue by iandees** [openaddresses/machine#232]
I've had multiple people in the last couple weeks ask about subaddressing/unit values. Let's add a column to the output CSV.

This will be things like apartment number, unit number, etc.

What do we think about calling it `unit`? Maybe more generically: `subaddress`?

**Comment by migurski** [comment]
I like unit, myself.

**Comment by stephenkhess** [comment]
Resolving this will clear up some issues we have at Mapzen with importing addresses.  For example, /us/pa/lancaster.csv has 450 entries for "300 Willow Valley Lakes Drive" that are identical with the exception of lat/lng fields.  I looked into the source data and found that this is an apartment building and each is an individually listed apartment.  Exposing the unit number would allow us to ignore apartments within a building since we're only concerned with the address of the building itself.

**Comment by migurski** [comment]
After [adding to the OA contribution guide](https://github.com/openaddresses/openaddresses/issues/1380), we will follow up with support in Machine.

**Comment by migurski** [comment]
Moving this work over to https://github.com/openaddresses/openaddresses/issues/1380.
