### ISSUE TITLE
US exports contain PO Boxes that aren't valid addresses 

### ISSUE THREAD

**Issue by stephenkhess** [openaddresses/machine#238]
Here are some examples of PO boxes I've found in the data:

```
ca/contra_costa_county.csv:-121.7530406,38.0197913,,P O Box 524,,,,,
co/mineral.csv:-105.9355554,37.1742049,,Po Box 9901,,,,,
co/mineral.csv:-105.8786383,37.15125,,C/O Leroy Salazar  Po Box 296,,,,,
```

Colorado and Kansas appear to be the biggest culprits (count is the first column):

```
admins-MBP-2% egrep -ri "p[ \.]?o[ \.]? +box" * | awk -F ':' '{ print $1 }' | sort | uniq -c
   1 ca/contra_costa_county.csv
   1 ca/san_bernardino_county.csv
   1 ca/santa_barbara_county.csv
3887 co/conejos.csv
   1 co/larimer.csv
3887 co/mineral.csv
  42 fl/_loveland.csv
   2 il/putnam.csv
2866 ks/johnson_county.csv
   3 mn/wilkin.csv
 255 nd/golden_valley_county.csv
   1 nm/bernalillo.csv
   4 nv/henderson.csv
   4 oh/lorain.csv
   2 tx/el_paso.csv
   1 tx/houston.csv
   1 wa/snohomish.csv
   1 wa/snohomish_county.csv
   2 wi/pierce.csv
```

**Comment by geobrando** [comment]
Hi @stephenkhess. I discovered this a while back and removed most of these sources as they likely represent billing addresses and not situs. Wondering if these current sources you found were added recently. I will have a look.

I have proposed adding some QC code that will flag suspect sources but haven't gotten around to it yet. Thanks.

**Comment by stephenkhess** [comment]
I realized that my data was 2 weeks old so I updated and ran again:

```
admins-MBP-2% egrep -ri "p[ \.]?o[ \.]? +box" * | awk -F ':' '{ print $1 }' | sort | uniq -c
   1 ca/contra_costa_county.csv
   1 ca/san_bernardino_county.csv
   1 ca/santa_barbara_county.csv
3887 co/conejos.csv
   1 co/larimer.csv
3887 co/mineral.csv
  42 fl/_loveland.csv
   2 il/putnam.csv
1434 ks/johnson_county.csv
   3 mn/wilkin.csv
 255 nd/golden_valley_county.csv
   1 nm/bernalillo.csv
   4 nv/henderson.csv
   4 oh/lorain.csv
   2 tx/el_paso.csv
   1 tx/houston.csv
   1 wa/snohomish.csv
   1 wa/snohomish_county.csv
   2 wi/pierce.csv
```

The 4 biggest PO Box sources were adding within the past 2 months.  

Is the idea to flat-out eliminate sources that contain PO Boxes or remove the PO Boxes but process the rest of the file?  There appears to be some good data in those sources among the PO Boxes.

**Comment by geobrando** [comment]
Well, both.

1. Eliminate entire sources that are billing or owner addresses, which typically result in a substantial number of PO Box addresses.  There are some good physical addresses there but it's impossible to tell which ones they are.  These are usually parcel polygon layers or point layers derived from parcel polygon layers that lack situs addresses.  You'll also find evidence of this by looking at the field names and in the metadata.  For example, `us/mt/mineral` uses a field called `"OwnerAddre"`.  You'll even see some addresses that are from completely different states or countries.  For those that are parcel polygons, the address data can be remove and a Parcel `id` number added as we've now expanded to collected parcels without addresses as well.

1.  As I explained before, it appears sometimes you'll say a few PO Box addresses present in otherwise valid sources.  These individual addresses could be removed as part of a larger QA effort.

**Comment by stephenkhess** [comment]
Makes sense, thanks for the info!

**Comment by geobrando** [comment]
No problem. Thanks for bringing this up!.

Also, let me correct myself and say that we're currently NOT accepting parcel layers without address `number` and `street`, but I think that's the plan.

I'll take a look at those 4 sources with a substantial number of PO boxes and see if they need to be changed to different fields or removed altogether.  Or if you'd like to go over them, go ahead.

**Comment by geobrando** [comment]
@stephenkhess FYI.. Here's my little experiment with R to investigate the same thing from earlier in the year

http://brandonknight.net/oa-pobox-qa/
