### ISSUE TITLE
Support new in-source tests

### ISSUE THREAD

**Issue by migurski** [openaddresses/machine#544]
A unit test-like syntax in sources will make it easier to develop and debug regular expressions.

- [x] Wait for merge on https://github.com/openaddresses/openaddresses/pull/2484

**Comment by migurski** [comment]
@iandees / @NelsonMinar, I'd love your thoughts on this and the linked PR!

**Comment by NelsonMinar** [comment]
Tests for source specs; what an awesome idea! I love that @trescube went ahead and designed it and implemented it. The basic design looks good to me.

I'm a little unclear on the format of the `inputs` field. For a CSV file I guess it's one line of a CSV? But what is it for a GeoJSON source or a Shapefile?

But I'm much less excited about bringing NodeJS back in to machine. But maybe that's not the long term plan? I saw your note about "using the same Machine code that does the actual work so that the test tests what we expect it to test". I think that's a fantastic idea, is that the goal? If so, maybe the "inputs" should really be a small excerpt of the original source? But I know from experience that's difficult to prepare.

**Comment by trescube** [comment]
Thanks!  

It's a little unclear for this particular source, but the `inputs` fields would be the column names from the original source.  The tests don't actually connect to the data source, the `inputs` are just mock values that are sent to the regexes.  For example, `alternativ` is the data field from the Czech countrywide source in the PR used for all of `number`, `street`, `city`, and `postcode` fields and the regexes operate on it.  It wouldn't matter if the source is CSV, GeoJSON, or Shapefile.  Another source that has two fields subject to regexes would have two fields in `inputs`.  

I wrote the test driver in node because I'm not terribly familiar with Python beyond the basics and didn't want to invest a lot of time in a proof of concept whereas I work with node primarily at mapzen/pelias.  I'm totally fine not using node for the long term strategy.  @migurski and I discussed using the actual machine to run and pass these preliminary tests as a condition to downloading and processing the entire source.  Additionally, extracting the machine `function`s that can be used as a library in local python-driven unit tests would offer even more immediate feedback (which is more important to me when refining regexes).  

The idea behind `inputs` is to emulate the standard and edge cases found in the source data for historical purposes and testing purposes.  Right now there's very little coverage of what types of inputs an OA contributor can expect to run across so modifying the rather complicated regexes can get dicey.  See [Churchill, NV](https://github.com/openaddresses/openaddresses/blob/master/sources/us/nv/churchill.json) and [Tacoma, WA](https://github.com/openaddresses/openaddresses/blob/master/sources/us/wa/city_of_tacoma.json) for sources that I added examples to.  Compare to [Vitebsk, Belarus](https://github.com/openaddresses/openaddresses/blob/master/sources/by/vitebsk/regionwide.json) for a source for harder-to-maintain regexes.  

In the short term, the plan would be to incorporate these tests into the larger node unit test framework, while starting work on transitioning the machine to run all the unit tests in python and the node tests would all go away.

**Comment by migurski** [comment]
I think the intent of the input is that it would contain the source fields as you suggest. In this case, Czech is a bit weird because its single source field "alternativ" looks like a line of CSV: https://s3.amazonaws.com/data.openaddresses.io/runs/153057/sample.json

A different source might look like this:

```
{
    "description": "Lorem ipsum dolor",
    "inputs": {
        "ADDR_NUM": "505",
        "ADDR_NUM_SUF": "",
        "NAME": "PLUM",
        "PREFIX_DIR": "",
        "PREFIX_TYPE": "",
        "SUFFIX_DIR": "",
        "TYPE": "ST",
        "ZIP_CODE": "42420-0000"
    },
    "expected": {
        …
```

**Comment by NelsonMinar** [comment]
Got it, the plan makes sense to me. The source test spec is simple enough I could imagine keeping multiple implementations, like Node and Python. I think it'd be valuable to have a tool anyone can easily run interactively while debugging source regexp. For that matter a little webapp would be pretty easy too.

(An aside, do you know about https://regex101.com/ ?)
