### ISSUE TITLE
Move test code into openaddr submodule?

### ISSUE THREAD

**Issue by migurski** [openaddresses/machine#60]
It’s currently in parts throughout the project, attached to `openaddr.cache`, `conform`, and elsewhere. Is that okay?

**Comment by NelsonMinar** [comment]
I think it's a mess the way it is, particularly what I did in openaddr.conform. Sorry! The right thing IMHO is to have a machine/test/test_conform.py file for the unit test code, just move it from the machine/openaddr/conform.py file. I did something odd where the conform unit tests are in three separate suites, because each has different setup/teardown requirements. I think it's OK to put all three in one file but don't care. Python's test suite management confuses me.

Really the only thing I care about is that it's easy to run a subset of the tests at a time. Sorry to leave this mess; I can clean it up but not for a few weeks. Or feel free to do whatever works now.

**Comment by migurski** [comment]
You're thinking it makes sense to move the tests outside the openaddr module altogether?

I don’t find anything weird about the three suites for conform, they behave well. It allows us to more easily run grouped tests.

**Comment by NelsonMinar** [comment]
It's just nice to separate test code from running code. Separate directories seems best to me.

**Comment by migurski** [comment]
I’ll leave it alone for the time being.

**Comment by migurski** [comment]
Started in 7a19387 and completed in 7b0abea.
