### ISSUE TITLE
Batch processing takes long time

### ISSUE THREAD

**Issue by stefanb** [openaddresses/machine#636]
Few days is a long time when most of the work seems not really needed.

In some countries data rarely changes, eg:
http://results.openaddresses.io/sources/cz/countrywide
and also the json changes rarely (often only when data is updated):
https://github.com/openaddresses/openaddresses/commits/HEAD/sources/cz/countrywide.json

http://results.openaddresses.io/sources/au/countrywide
https://github.com/openaddresses/openaddresses/commits/HEAD/sources/au/countrywide.json

And in some countries data and json _never_ change, eg:
http://results.openaddresses.io/sources/ee/countrywide
https://github.com/openaddresses/openaddresses/commits/HEAD/sources/ee/countrywide.json

There are probably many such cases.

`process_one.py` makes no attempt to check if there were any significant changes since the last processing was done. It would make sense to check:
* hash of source json change
* hash of downloaded data change
* code changed significantly (process, DB schema, requiring re-processing)

https://github.com/openaddresses/machine/blob/HEAD/openaddr/process_one.py

This should also help lower the EC2 usage and cost.

**Comment by migurski** [comment]
Thanks for the comment!

We’ve thought about this a bit before, and decided against some of these optimizations. The biggest reason is that downloading cached data takes a majority of processing time, and it’s necessary to download it in order to determine if it’s changed. It would save us a small amount of CPU, but probably not much time.

We use the code version as part of the cache key, though we don't attempt to determine what a significant change might be.

I have recently extended the keep time for runs from five days to ten, in the hopes that we can run the batch process twice as often to get new sources onto the front page faster while decreasing the overall time working.

**Comment by iandees** [comment]
One thing I've thought about is extending the caching implementations to optionally support a "fetch since" system with arbitrary "since-ness" stored by `machine`.

For example, the HTTP cacher could store the `Date` response header of the HTTP download request and send the `If-Modified-Since` on subsequent requests. That way, the server could tell the cacher that nothing has changed and the cacher could tell the rest of the system that nothing has changed.

Another example would be the Esri cacher. Some layers support a [`returnUpdates`](http://resources.arcgis.com/en/help/rest/apiref/layer.html) feature that we might be able to use to only return rows that have changed since the last time we processed the source.

And of course the 'fallback' case would be that we always cache and process everything like we do now.

**Comment by migurski** [comment]
If we can make the ESRI cacher do this, it’d be pretty interesting. I believe the long times required for that to run contribute to the majority of our waiting-around times.
